services:
  backend:
    build:
      context: .
    ports:
      - 3000:3000
  database:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5555:5432"
volumes:
  pgdata: